name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Create catalog env
        run: mkdir env

      - name: Create file env
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "env/.env.local"
          FILE_BASE64: "UkVBQ1RfQVBQX0JBU0VfVVJMPWh0dHA6Ly9sb2NhbGhvc3Q6ODAwMS8="

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: build
          folder: build
